services:
  - type: web
    name: astrochino
    runtime: docker
    repo: https://github.com/SmartModefun/astrochino-app
    branch: main
    plan: starter
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DB_PATH
        value: /data/astrochino.db
      - key: PAYPAL_SANDBOX
        value: "true"
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
